name: 'name_generator'
version: '1.0.0'
config-version: 2

profile: 'name_generator'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  name_generator:
    raw_names:
      +column_types:
        id: integer
        user_id: uuid
        birthdate: date
        created_at: timestamp
    raw_sales_transactions:
      +column_types:
        transaction_id: integer
        user_id: uuid
        product_id: integer
        order_date: timestamp
        quantity: integer
        unit_price: decimal(10,2)
        total_amount: decimal(10,2)
    raw_products:
      +column_types:
        product_id: integer
        unit_price: decimal(10,2)

models:
  name_generator:
    staging:
      +materialized: view
    marts:
      +materialized: table
